let emp=[
    {"id":1,"name":"Kendal","email":"kkowal0@fotki.com","gender":"Male"},
{"id":2,"name":"Bryna","email":"bcoenraets1@reuters.com","gender":"Female"},
{"id":3,"name":"Terrell","email":"taggett2@house.gov","gender":"Male"},
{"id":4,"name":"Fianna","email":"fgibling3@yahoo.com","gender":"Female"},
{"id":5,"name":"Dorthea","email":"droof4@soup.io","gender":"Female"},
{"id":6,"name":"Hervey","email":"hbruckstein5@aboutads.info","gender":"Male"},
{"id":7,"name":"Jemie","email":"jposkitt6@privacy.gov.au","gender":"Female"},
{"id":8,"name":"Bernelle","email":"bewin7@hc360.com","gender":"Female"},
{"id":9,"name":"Teddie","email":"tforsdike8@mit.edu","gender":"Male"},
{"id":10,"name":"Cheri","email":"cryves9@soundcloud.com","gender":"Female"},
{"id":11,"name":"Filmore","email":"felcoatea@privacy.gov.au","gender":"Male"},
{"id":12,"name":"Joanna","email":"jberzonsb@newyorker.com","gender":"Female"},
{"id":13,"name":"Ernestus","email":"elateyc@reuters.com","gender":"Male"},
{"id":14,"name":"Blayne","email":"bcodrond@ning.com","gender":"Male"},
{"id":15,"name":"Perry","email":"pcrawe@github.io","gender":"Female"},
{"id":16,"name":"Noe","email":"ngeckef@vinaora.com","gender":"Bigender"},
{"id":17,"name":"Camella","email":"charrismithg@shareasale.com","gender":"Female"},
{"id":18,"name":"Timmy","email":"taucoateh@123-reg.co.uk","gender":"Male"},
{"id":19,"name":"Penni","email":"pmotei@mozilla.com","gender":"Female"},
{"id":20,"name":"Vick","email":"vubachj@flickr.com","gender":"Male"},
{"id":21,"name":"Cleo","email":"candrick@soundcloud.com","gender":"Female"},
{"id":22,"name":"Guillermo","email":"ghakesl@w3.org","gender":"Male"},
{"id":23,"name":"Cos","email":"cshoreym@latimes.com","gender":"Male"},
{"id":24,"name":"Hewie","email":"hholseyn@vinaora.com","gender":"Male"},
{"id":25,"name":"Hamlin","email":"hslaineyo@altervista.org","gender":"Non-binary"},
{"id":26,"name":"Gerry","email":"gpenimanp@liveinternet.ru","gender":"Female"},
{"id":27,"name":"Keefe","email":"kbelfieldq@nytimes.com","gender":"Male"},
{"id":28,"name":"Noah","email":"nseabonr@scribd.com","gender":"Agender"},
{"id":29,"name":"Rycca","email":"rsacases@eepurl.com","gender":"Female"},
{"id":30,"name":"Alyce","email":"aleinstert@rambler.ru","gender":"Female"},
{"id":31,"name":"Christabella","email":"ccaselliu@accuweather.com","gender":"Female"},
{"id":32,"name":"Marion","email":"mreefv@jiathis.com","gender":"Male"},
{"id":33,"name":"Keslie","email":"kberlingw@mapquest.com","gender":"Female"},
{"id":34,"name":"Reba","email":"rstarsmearex@exblog.jp","gender":"Female"},
{"id":35,"name":"Brande","email":"bbarehamy@apache.org","gender":"Female"},
{"id":36,"name":"Marietta","email":"mmcsheez@moonfruit.com","gender":"Female"},
{"id":37,"name":"Analise","email":"afaithfull10@irs.gov","gender":"Female"},
{"id":38,"name":"Austina","email":"asima11@blog.com","gender":"Polygender"},
{"id":39,"name":"Waiter","email":"wcromack12@wordpress.com","gender":"Male"},
{"id":40,"name":"Susana","email":"sjervis13@imdb.com","gender":"Female"},
{"id":41,"name":"Claudie","email":"cmadner14@mashable.com","gender":"Female"},
{"id":42,"name":"Maible","email":"mgane15@stumbleupon.com","gender":"Female"},
{"id":43,"name":"Francesca","email":"fbydaway16@mapquest.com","gender":"Female"},
{"id":44,"name":"Lyell","email":"lgeri17@eventbrite.com","gender":"Agender"},
{"id":45,"name":"Hugibert","email":"hwardhough18@tuttocitta.it","gender":"Non-binary"},
{"id":46,"name":"Logan","email":"lbohlmann19@webeden.co.uk","gender":"Male"},
{"id":47,"name":"Ninette","email":"nmuscat1a@delicious.com","gender":"Female"},
{"id":48,"name":"Vail","email":"vspenceley1b@usgs.gov","gender":"Bigender"},
{"id":49,"name":"Lancelot","email":"lizakof1c@cloudflare.com","gender":"Male"},
{"id":50,"name":"Delphine","email":"dbamlett1d@fema.gov","gender":"Female"},
]
let e1=emp.filter((emp)=>{
    return emp.gender=="Male"
});
console.log(e1);




